parameters:
#    memories_box.example.class: Memories\BoxBundle\Example

services:
#    memories_box.example:
#        class: %memories_box.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
